# Cloud Build for qrl-api with Cloud Run deployment + Scheduler jobs
substitutions:
  _IMAGE_URI: "asia-southeast1-docker.pkg.dev/qrl-api/qrl-trading-api/qrl-trading-api:latest"

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_URI}'
      - '.'

  # 2️⃣ Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_URI}'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'qrl-trading-api'
      - '--image=${_IMAGE_URI}'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--concurrency=80'
      - '--timeout=300s'
      - '--cpu-boost'
      - '--set-secrets=MEXC_API_KEY=mexc-api-key:latest,MEXC_SECRET_KEY=mexc-secret-key:latest,REDIS_URL=redis-url:latest'

  # 4️⃣ Enable necessary APIs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'enable-apis'
    args:
      - 'services'
      - 'enable'
      - 'cloudscheduler.googleapis.com'
      - 'appengine.googleapis.com'

  # 5️⃣ Delete old Scheduler jobs (if exist)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-01-min-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'delete'
      - '01-min-job'
      - '--location=asia-southeast1'
      - '--quiet'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-05-min-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'delete'
      - '05-min-job'
      - '--location=asia-southeast1'
      - '--quiet'
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'delete-15-min-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'delete'
      - '15-min-job'
      - '--location=asia-southeast1'
      - '--quiet'

  # 6️⃣ Create Scheduler jobs
  # Job 1 - Balance sync every minute
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-sync-balance-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - '01-min-job'
      - '--location=asia-southeast1'
      - '--schedule=* * * * *'
      - '--uri=https://qrl-trading-api-545492969490.asia-southeast1.run.app/tasks/sync-balance'
      - '--http-method=POST'
      - '--headers=X-CloudScheduler=true'
      - '--headers=Content-Type=application/json'
      - '--message-body={}'
      - '--time-zone=Asia/Taipei'
      - '--description=Sync MEXC account balance to Redis every 1 minute'
      - '--attempt-deadline=60s'
      - '--max-retry-attempts=3'
      - '--min-backoff-duration=5s'
      - '--max-backoff-duration=60s'

  # Job 2 - Update price every 5 minutes
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-update-price-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - '05-min-job'
      - '--location=asia-southeast1'
      - '--schedule=*/5 * * * *'
      - '--uri=https://qrl-trading-api-545492969490.asia-southeast1.run.app/tasks/update-price'
      - '--http-method=POST'
      - '--headers=X-CloudScheduler=true'
      - '--headers=Content-Type=application/json'
      - '--message-body={}'
      - '--time-zone=Asia/Taipei'
      - '--description=Update QRL/USDT price from MEXC every 5 minutes'
      - '--attempt-deadline=60s'
      - '--max-retry-attempts=3'
      - '--min-backoff-duration=5s'
      - '--max-backoff-duration=60s'

  # Job 3 - Update cost every 15 minutes
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-update-cost-job'
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - '15-min-job'
      - '--location=asia-southeast1'
      - '--schedule=*/15 * * * *'
      - '--uri=https://qrl-trading-api-545492969490.asia-southeast1.run.app/tasks/update-cost'
      - '--http-method=POST'
      - '--headers=X-CloudScheduler=true'
      - '--headers=Content-Type=application/json'
      - '--message-body={}'
      - '--time-zone=Asia/Taipei'
      - '--description=Update cost and PnL calculations every 15 minutes'
      - '--attempt-deadline=60s'
      - '--max-retry-attempts=3'
      - '--min-backoff-duration=5s'
      - '--max-backoff-duration=60s'

  # 7️⃣ List jobs for verification
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'list-jobs'
    args:
      - 'scheduler'
      - 'jobs'
      - 'list'
      - '--location=asia-southeast1'

  # 8️⃣ Test trigger jobs
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'test-jobs'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for Cloud Run to be ready..."
        sleep 30
        echo "Triggering scheduler jobs..."
        gcloud scheduler jobs run 01-min-job --location=asia-southeast1 || true
        sleep 5
        gcloud scheduler jobs run 05-min-job --location=asia-southeast1 || true
        sleep 5
        gcloud scheduler jobs run 15-min-job --location=asia-southeast1 || true
        echo "All jobs triggered successfully"

# Timeout for the entire build
timeout: 1800s

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY
