# Minimal Cloud Build for qrl-api
# Build Docker image, push to Container Registry, deploy to Cloud Run

steps:
  # 1️⃣ Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/qrl-api/qrl-trading-api/qrl-trading-api:latest'
      - '.'

  # 2️⃣ Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/qrl-api/qrl-trading-api/qrl-trading-api:latest'

  # 3️⃣ Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'qrl-trading-api'
      - '--image=asia-southeast1-docker.pkg.dev/qrl-api/qrl-trading-api/qrl-trading-api:latest'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      # Resource limits
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--concurrency=80'
      - '--timeout=300s'
      # Environment variables from Secret Manager
      - '--set-env-vars=REDIS_URL=$$REDIS_URL'
      - '--set-secrets=MEXC_API_KEY=mexc-api-key:latest,MEXC_SECRET_KEY=mexc-secret-key:latest'

# Timeout for the entire build
timeout: 1200s
